/* Enum value -> the label the student actually saw on the decision form.
 *
 * The firm dashboard was rendering raw enums (STABILIZE_MAP,
 * OT_VISIBILITY_ASSESSMENT, PURSUE) where an instructor needs to read what the
 * team chose. These are extracted verbatim from the backend week specs
 * (weeks/week*.py), which remain the source of truth — 112 values, no
 * conflicts across the fourteen weeks.
 *
 * To refresh after a week's choices change, re-extract from those specs rather
 * than editing by hand.
 */

const CHOICE_LABELS = {
  absorb: "Absorb",
  balanced_split: "Balanced split",
  bet: "Bet",
  blame_shift: "Blame shift",
  board_language: "Board language",
  build_differentiating_rent_commodity: "Build differentiating, rent commodity",
  build_everything: "Build everything",
  calloway: "Calloway",
  centralize: "Centralize",
  chase: "Chase",
  closed: "Closed",
  coherent: "Coherent",
  commit_finish: "Commit to finish",
  committed_spend_discount: "Committed-spend discount",
  concede: "Concede",
  connected_services: "Connected services",
  contained: "Contained",
  continue: "Continue",
  contradictory: "Contradictory",
  core_context_split: "Core/context split",
  defend: "Defend",
  defended: "Defended",
  defer: "Defer",
  descope: "Descope",
  describes_unbuilt_company: "Describes unbuilt company",
  descriptive_only: "Descriptive only",
  diagnose_only: "Diagnose only",
  duck: "Duck",
  edge_and_repatriate: "Edge and repatriate",
  embedded: "Embedded",
  ferraro: "Ferraro",
  fight: "Fight",
  fischer: "Fischer",
  folded: "Folded",
  genuine: "Genuine",
  governed_with_plan: "Governed with plan",
  grand_platform: "Grand platform",
  grand_spend: "Grand spend",
  grounded_in_real_position: "Grounded in real position",
  hedge: "Hedge",
  hedge_further: "Hedge further",
  hedged: "Hedged",
  hold_firm: "Hold firm",
  honest: "Honest",
  ignore: "Ignore",
  kill: "Kill",
  land_grab: "Land grab",
  linear: "Linear",
  minimal: "Minimal",
  minimal_change: "Minimal change",
  multi_vendor: "Multi-vendor",
  narrow_ecosystem: "Narrow ecosystem",
  narrow_real: "Narrow real use cases",
  none: "None",
  open_unguarded: "Open unguarded",
  ot_visibility_assessment: "OT visibility assessment",
  other_credibility_move: "Other credibility move",
  overwhelmed: "Overwhelmed",
  own: "Own",
  papered_over: "Papered over",
  parallel: "Parallel",
  partial: "Partial",
  pause_assess: "Pause and assess",
  pay: "Pay",
  petrillo: "Petrillo",
  pilot: "Pilot",
  portability_protected: "Portability protected",
  predictive: "Predictive",
  predictive_maintenance_core: "Predictive maintenance core",
  premature_bold_move: "Premature bold move",
  propose_safe_stabilization: "Propose safe stabilization",
  pure_product: "Pure product",
  pursue: "Pursue",
  push_bold_raw: "Push bold raw",
  reframe_and_offer: "Reframe and offer",
  refuse: "Refuse",
  reinhardt: "Reinhardt",
  renegotiate: "Renegotiate",
  rent: "Rent",
  rent_cheapest: "Rent cheapest",
  rent_everything: "Rent everything",
  replace: "Replace",
  rescue: "Rescue existing cutover",
  restructure: "Restructure",
  right_sized: "Right-sized",
  scoped_with_data_rights: "Scoped with data rights",
  separate_group: "Separate group",
  settle_where_serves: "Settle where serves",
  shared_value: "Shared value",
  single_hyperscaler: "Single hyperscaler",
  slow_walk: "Slow-walk",
  spin: "Spin",
  spin_or_hide: "Spin or hide",
  stabilize: "Stabilize",
  stabilize_map: "Stabilize and map dependencies",
  strategic_conviction: "Strategic conviction",
  sweet_deal_as_written: "Sweet deal as written",
  switch: "Switch",
  take_accelerator: "Take accelerator",
  team_recommendation_with_cover: "Team recommendation with cover",
  technical_jargon: "Technical jargon",
  theater_scatter: "Theater scatter",
  too_big: "Too big",
  too_small: "Too small",
  tran: "Tran",
  transform_data_services: "Transform to data and services",
  transparent: "Transparent",
  transparent_ownership: "Transparent ownership",
  ungoverned: "Ungoverned",
  victory_narrative: "Victory narrative",
  watch: "Watch",
  well_sized: "Well sized"
};

/** The student-facing label for a stored choice value, or a humanised fallback. */
export function choiceLabel(value) {
  if (typeof value !== "string") return value;
  if (CHOICE_LABELS[value]) return CHOICE_LABELS[value];
  // Unknown value: at least don't shout an enum at the reader.
  return value.replace(/_/g, " ").replace(/^\w/, (c) => c.toUpperCase());
}

export default CHOICE_LABELS;
